name: product_challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  google_fonts: ^2.1.0
  flutter_modular: ^4.5.1+1
  flutter_svg: ^1.0.3
  flutter_rating_bar: ^4.0.0
  cloud_firestore: ^3.1.14
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.12
  image_picker: ^0.8.5
  mobx: ^2.0.5
  flutter_mobx: ^2.0.5

  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.1+3
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mocks/products.json
